const example_2_2_1 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="552" y="65"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0-0-000-</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value><next><block type="create_measure_match_zero" id="+k1G`7d=]4GGa7_8.MH+"><value name="MEASURE"><block type="math_number" id="urpW-4Fh2[2OZIA_YC@6"><field name="NUM">2</field></block></value><value name="TIMBRE"><block type="text" id="gSG!9w24zWjvf#jzb-i#"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="v_?Q,:y;V:Ny0Ga^CBT5"><field name="TEXT">C4,C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="c$r}JoEpl0!E{+fk?JuW"><field name="TEXT">0000000-</field></block></value><value name="VELOCITY"><block type="text" id="-,X~%EFtdbpxJB1YE:K1"><field name="TEXT"></field></block></value></block></next></block></xml>';
const example_2_2_2 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="441" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">A4,A4,G4,A4,C5</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">00-00-0-</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value><next><block type="create_measure_match_zero" id="+k1G`7d=]4GGa7_8.MH+"><value name="MEASURE"><block type="math_number" id="urpW-4Fh2[2OZIA_YC@6"><field name="NUM">2</field></block></value><value name="TIMBRE"><block type="text" id="gSG!9w24zWjvf#jzb-i#"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="v_?Q,:y;V:Ny0Ga^CBT5"><field name="TEXT">A4,C5,A4,G4,E4</field></block></value><value name="BEAT"><block type="text" id="c$r}JoEpl0!E{+fk?JuW"><field name="TEXT">00000---</field></block></value><value name="VELOCITY"><block type="text" id="-,X~%EFtdbpxJB1YE:K1"><field name="TEXT"></field></block></value></block></next></block></xml>';

const example_2_2_3 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="441" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">D4,E4,E4,E4,E4,D4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0--00-0-0-00</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value><next><block type="create_measure_match_zero" id="+k1G`7d=]4GGa7_8.MH+"><value name="MEASURE"><block type="math_number" id="urpW-4Fh2[2OZIA_YC@6"><field name="NUM">2</field></block></value><value name="TIMBRE"><block type="text" id="gSG!9w24zWjvf#jzb-i#"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="v_?Q,:y;V:Ny0Ga^CBT5"><field name="TEXT">A3,C4,D4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="c$r}JoEpl0!E{+fk?JuW"><field name="TEXT">0--00-0-0---</field></block></value><value name="VELOCITY"><block type="text" id="-,X~%EFtdbpxJB1YE:K1"><field name="TEXT"></field></block></value></block></next></block></xml>';
const example_2_2_4 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="441" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0--00-0-</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value><next><block type="create_measure_match_zero" id="+k1G`7d=]4GGa7_8.MH+"><value name="MEASURE"><block type="math_number" id="urpW-4Fh2[2OZIA_YC@6"><field name="NUM">2</field></block></value><value name="TIMBRE"><block type="text" id="gSG!9w24zWjvf#jzb-i#"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="v_?Q,:y;V:Ny0Ga^CBT5"><field name="TEXT">C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="c$r}JoEpl0!E{+fk?JuW"><field name="TEXT">00-00-0-</field></block></value><value name="VELOCITY"><block type="text" id="-,X~%EFtdbpxJB1YE:K1"><field name="TEXT"></field></block></value></block></next></block></xml>';
const example_2_2_5 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="441" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">00-00000</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value><next><block type="create_measure_match_zero" id="+k1G`7d=]4GGa7_8.MH+"><value name="MEASURE"><block type="math_number" id="urpW-4Fh2[2OZIA_YC@6"><field name="NUM">2</field></block></value><value name="TIMBRE"><block type="text" id="gSG!9w24zWjvf#jzb-i#"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="v_?Q,:y;V:Ny0Ga^CBT5"><field name="TEXT">C4,C4,C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="c$r}JoEpl0!E{+fk?JuW"><field name="TEXT">00-00000</field></block></value><value name="VELOCITY"><block type="text" id="-,X~%EFtdbpxJB1YE:K1"><field name="TEXT"></field></block></value></block></next></block></xml>';
const example_2_12_1 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="580" y="14"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,D4,E4,F4,G4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">00000</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value><next><block type="create_measure_match_zero" id="CSk+H*{K=/F)vK=+_7E/"><value name="MEASURE"><block type="math_number" id="_.;uu`mcIY]~jmaI0LD4"><field name="NUM">2</field></block></value><value name="TIMBRE"><block type="text" id="j$}mEhm%WQ]mnHk1Ed;X"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="=ZY]1CC)[bqj/i!w*:x6"><field name="TEXT">A4,G4,E4,D4,C4</field></block></value><value name="BEAT"><block type="text" id="+tKs^OoZI}kws/?}bL86"><field name="TEXT">00000</field></block></value><value name="VELOCITY"><block type="text" id="DcD#?}$Y9=[NsgiPBw`w"><field name="TEXT"></field></block></value></block></next></block></xml>';
const example_2_12_2 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="456" y="6"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,D4,E4,F4,G4,A4,B4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0000000</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT">1,1,1,1,0.5,0.5,0.5</field></block></value><next><block type="create_measure_match_zero" id="CSk+H*{K=/F)vK=+_7E/"><value name="MEASURE"><block type="math_number" id="_.;uu`mcIY]~jmaI0LD4"><field name="NUM">2</field></block></value><value name="TIMBRE"><block type="text" id="j$}mEhm%WQ]mnHk1Ed;X"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="=ZY]1CC)[bqj/i!w*:x6"><field name="TEXT">C5,B4,A4,G4,F4,E4,D4</field></block></value><value name="BEAT"><block type="text" id="+tKs^OoZI}kws/?}bL86"><field name="TEXT">0000000</field></block></value><value name="VELOCITY"><block type="text" id="DcD#?}$Y9=[NsgiPBw`w"><field name="TEXT">1,1,1,1,0.5,0.5,0.5</field></block></value></block></next></block></xml>';
export default {
  example_2_2_1,
  example_2_2_2,
  example_2_2_3,
  example_2_2_4,
  example_2_2_5,
  example_2_12_1,
  example_2_12_2
};
