const example_3_9_1 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="f8`Kt_$U;WA{%2=vGCAs" x="377" y="74"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,D4,E4,F4,G4,A4,B4,C5</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">00000000</field></block></value></block></xml>';

const example_3_9_2 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_on_scale_match_zero_new" id="l[W#Ppg-L|,rg3G-)PZ~" x="220" y="181"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">1,2,3,4,5,6,7,1\'</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">00000000</field></block></value><value name="SCALE"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value><value name="BASENOTE"><block type="text" id="LwK8ZfHO~5gvQ4-a%BzO"><field name="TEXT">C3</field></block></value></block></xml>';

const example_3_14_1 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_track" id="]Ar|8{@G:Q:u6N]Xi9C7" x="561" y="129"><value name="TIMBRE"><block type="text" id="]HuWnVu5~K/l7/a]BOiX"><field name="TEXT">piano</field></block></value><value name="TEMPO"><block type="math_number" id="HyFckejpS}[ncuMiGE,e"><field name="NUM">120</field></block></value><value name="VOLUMN"><block type="math_number" id="QF{9xu-b?5Q^`9z[|:{M"><field name="NUM">100</field></block></value><statement name="measures"><block type="create_measure_match_zero_new" id="f8`Kt_$U;WA{%2=vGCAs" x="654" y="43"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">D5,G4,A4,B4,C5</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0-0000</field></block></value><next><block type="create_measure_match_zero_new" id="5{HIS6/I7qc9N7w/MltC"><value name="MEASURE"><block type="math_number" id=";H(^Ytv{FP$fy~o(l+AL"><field name="NUM">1</field></block></value><value name="SEQUENCE"><block type="text" id="1v,V-WOYndWQfq=]~ILz"><field name="TEXT">[G3,B3,D4],A3</field></block></value><value name="BEAT"><block type="text" id="7Q$+S=|.8[p-(sQP8$8}"><field name="TEXT">0---0-</field></block></value><next><block type="create_measure_match_zero_new" id="=U3B_`xzAfdC%lwTGWpK"><value name="MEASURE"><block type="math_number" id="geZWRRWq!s|kM)[?%SYI"><field name="NUM">2</field></block></value><value name="SEQUENCE"><block type="text" id="gL2Z=UyEaHgn@`1(@w},"><field name="TEXT">D5,G4,G4</field></block></value><value name="BEAT"><block type="text" id="cyIU.|XH%`IoafYFFu=;"><field name="TEXT">0-0-0-</field></block></value><next><block type="create_measure_match_zero_new" id="Mp2*RnK73)~:W$?t=AL/"><value name="MEASURE"><block type="math_number" id="k%JPX0C_e.:CLmG.5J*1"><field name="NUM">2</field></block></value><value name="SEQUENCE"><block type="text" id="a]3Py,wqINfFCr1N3wQ+"><field name="TEXT">B3</field></block></value><value name="BEAT"><block type="text" id="nZt;1ipUdR6b63D6|L#;"><field name="TEXT">0-----</field></block></value></block></next></block></next></block></next></block></xml>';

export default {
  example_3_9_1,
  example_3_9_2,
  example_3_14_1
};
