const example_1_5_1 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="546" y="94"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0---------------</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value></block></xml>';

const example_1_5_2 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="527" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0-------0-------</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value></block></xml>';
const example_1_5_3 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="527" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0---0---0---0---</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value></block></xml>';
const example_1_5_4 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="527" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0-0-0-0-0-0-0-0-</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value></block></xml>';
const example_1_5_5 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="527" y="68"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0000000000000000</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value></block></xml>';
const example_1_5_6 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="491" y="40"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">00000000000000000000000000000000</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value></block></xml>';

const example_1_17 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="390" y="182"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">triangle</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0--0</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value></block></xml>';
const example_1_23 =
  '<xml xmlns="http://www.w3.org/1999/xhtml"><variables></variables><block type="create_measure_match_zero" id="f8`Kt_$U;WA{%2=vGCAs" x="546" y="29"><value name="MEASURE"><block type="math_number" id=".WFT-Q(3,#GaZQpi)Ko4"><field name="NUM">1</field></block></value><value name="TIMBRE"><block type="text" id="1bTJTmzU$8IewRVRPZJU"><field name="TEXT">piano</field></block></value><value name="SEQUENCE"><block type="text" id="UZUasc$rVxqqNM-W.KRX"><field name="TEXT">C4,C4,C4,C4,C4,C4</field></block></value><value name="BEAT"><block type="text" id="a`Yd*qF4[?rbxnxx!N,R"><field name="TEXT">0--0--0--000</field></block></value><value name="VELOCITY"><block type="text" id="I5jC?yo9LAxSgDEiS7u["><field name="TEXT"></field></block></value></block></xml>';

export default {
  example_1_5_1,
  example_1_5_2,
  example_1_5_3,
  example_1_5_4,
  example_1_5_5,
  example_1_5_6,
  example_1_17,
  example_1_23
};
